### ISSUE TITLE
I am getting an abort() assertion when running a build compiled with VS 2019

### ISSUE THREAD

**Issue by Zero3K** [BenjaminKim/FileSystemTest#10]
I tried running it on Windows 10 (x64) and Windows 7 (x86). Both OSes show the same assertion.

**Comment by BenjaminKim** [comment]
This project supports VS 2022. If you have to use VS 2019, try this [commit](eec41d3a75607dd721747f40867eec27d5c55346)

**Comment by Zero3K** [comment]
![image](https://github.com/BenjaminKim/FileSystemTest/assets/6194332/d7d5c49d-c7b6-4f7a-8724-093c36826993)

**Comment by BenjaminKim** [comment]
@Zero3K What kind of Windows do you use?
That doesn't look like Windows 7 or Windows 10.
[SetFileInformationByHandle](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-setfileinformationbyhandle) is an API available since Windows Vista and later.

**Comment by Zero3K** [comment]
It is Windows 7.  I am using the Classic Theme.

**Comment by BenjaminKim** [comment]
The assert fails with this code.
```
    BOOL fOk = FileTimeToSystemTime(&localFileTime, &st);
    assert(fOk);
```

I don't know why `FileTimeToSystemTime` failed in your filesystem.
(What kind of filesystem are you test on?)

Try `GetLastError()` to figure it out. 
```
    BOOL fOk = FileTimeToSystemTime(&localFileTime, &st);
    // Use GetLastError why function fails.
    assert(fOk);
```

**Comment by Zero3K** [comment]
NTFS

**Comment by Zero3K** [comment]
Why did you close it?

**Comment by BenjaminKim** [comment]
If you want me to help you, start by investigating why the FileTimeToSystemTime function failed.

**Comment by Zero3K** [comment]
How do I do that? I am not a programmer.

**Comment by Zero3K** [comment]
Maybe you could make a new commit for debugging this issue further.

**Comment by Zero3K** [comment]
Is adding GetLastError() before the abort enough?
