### ISSUE TITLE
Translates test cases description to English.

### ISSUE THREAD

**Issue by BenjaminKim** [BenjaminKim/FileSystemTest#4]

**Comment by pmalhaire** [comment]
hello,
the log in Korean I guess is creating a runtime issue in my machine, commenting it corrected the issue  
https://github.com/BenjaminKim/FileSystemTest/blob/master/TestUnit/FileManagement/TestCopyFile.cpp#L72

**Comment by BenjaminKim** [comment]
Okay, this is the time to work again. Thank you :)

**Comment by pmalhaire** [comment]
thank you your tests are really usefull

**Comment by pmalhaire** [comment]
I am looking at the best way to compare 2 test run
by not showing the file times

**Comment by BenjaminKim** [comment]
@pmalhaire There is an option not to showing the file time. You should use that option compare 2 tests. I will write about options you can use to README.md.
